language: python
python:
      - "3.6"
    
branches:
#  only:
#    - master
    
install:
    - pip install -r backend/requirements.txt
    
script:
    - python backend/manage.py test
    
    
notifications:
  email:
    recipients:
      - rainy_waltz@naver.com
      
      
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: kucctimetable-webservice-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: kucc-2019-1/kucc-timetable #Github 주소
      branch: master
      
      
#test 3