language: python
python:
      - "3.6"
#    services:
#      - mysql
env:
    -DJANGO=2.1.4
    
install:
    - pip install -r backend\requirements.txt
    
script:
    - backend\python manage.py runserver