# Generated by Django 2.1.4 on 2019-04-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeindex',
            name='time_index_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
